### ISSUE TITLE
Current version of CAL not compatible with current version of EKP

### ISSUE THREAD

**Issue by Julians42** [CliMA/ClimaCalibrate.jl#108]
Currently CAL restricts EKP to v1 but v2 is now available. Installing EKP and then CAL leads to a package conflict error. `dev`ing works fine so far

Suggest bumping compat / allowing for EKP v2 as currently package requirements are incompatible. I don't think there are any breaking changes... 

@odunbar thoughts?

**Comment by nefrathenrici** [comment]
closed by #109
